nama = "Shin Tae Yong"
Umur = 21
nilaiAlpro = 90.1

hasil = f"Name saya,(nama) umur saya (Umur) dan Nilai Alpro saya (nilaiAlpro)"

print (hasil)
print ("Nama Saya", nama, "Umur :", (Umur), "Nilai Alpro: ", nilaiAlpro)
       
mandi = input ("Apakah kamu sudah mandi? ")
cuaca = input ("Cuaca sekarang seperti apa? ")

if mandi == "sudah" and cuaca == "cerah":
    print("ayo berangkat ngampus")

    bilangan1 = (input ("Masukan Bilangan pertama: "))
    bilangan2 = (input ()