nama1 = "dhani"
nama2 = "kusuma"
alamat1 = "lamongan"
alamat2 = "gresik"
angkatan1 = 24
angkatan2 = 24

print("disuatu jam selesai matkul ada dua orang maba yang bertemu mereka saling berkenalan dan saling menyapa")

print("kusuma : siapa namamu?")
print("dhani : namaku",nama1)

print("dhani : dan siapa namamu?")
print("kusuma : namaku", nama2)

print("kusuma : eh kamu alamatnya dimana?")
print("dhani : aku berasal dari" , alamat1)

print("dhani : emmm, kamu alamatnya dimana? ")
print("kusuma : aku berasal dari" , alamat2)

print("kusuma : eh dhani, em kamu angkatan berapa ya")
print("dhani : aku angkatan ",angkatan1)

print("dhani : lah kalo kamu kusuma, angkatan berapa? ")
print("kusuma : aku juga angkatan ",angkatan2)

dhani = input("dhani : eh kok cuaca nya panas, ayo ke kantin buat beli es? ")
kusuma = input("kusuma : iyanih,aku juga lapar ayo ke kantin? ")

if dhani == "ayo" and kusuma == "oke":
    print("gaskeun ke warung") 

print("akhirnya mereka ke kantin untuk berteduh dan makan")